//
//  Constants.swift
//  Boxii
//
//  Created by Chen Yu Tsen on 6/15/14.
//  Copyright (c) 2014 BoxiiApp. All rights reserved.
//

import Foundation
let PARSE_API_KEY = "Tfvv3aMCLTZJ4eXsRt7pb0EQ905YXdzyMvGdA80E"
let PARSE_APP_ID = "DzckuvCrYQogpmlJGWCanyYESHoxBQwSUVCvuTQa"

/*Notifications*/
let NOTIFICATION_REGISTRATION_SUCCESS = "NOTIFICATION_REGISTRATION_SUCCESS"
let NOTIFICATION_LOGIN_SUCCESS = "NOTIFICATION_LOGIN_SUCCESS"
let NOTIFICATION_ERROR = "NOTIFICATION_ERROR"

/*Segues*/
let SEGUE_REGISTRATION_TO_PROFILE = "FROM_REGISTRATION_TO_PROFILE_PIC"
let SEGUE_LOGIN_TO_MY_BOXII = "FROM_LOGIN_TO_MY_BOXII"
let SEGUE_PROFILE_TO_MY_BOXII = "FROM_PROFILE_PIC_TO_MY_BOXII"
let SEGUE_SPLASH_TO_MY_BOXII = "FROM_SPLASH_TO_MY_BOXII"
let SEGUE_SPLASH_TO_SIGNUP = "from_splash_to_signup"
let SEGUE_SPLASH_TO_LOGIN = "from_splash_to_login"